### ISSUE TITLE
Link failure

### ISSUE THREAD

**Issue by XinArkh** [a-mohsen/RoboticArmAutomation#1]
Thank you for your work on owi535. The link you post about [the D-H parameters and arm's forward kinematics](https://www.iaescore.com/journals/index.php/IJRA/article/view/1001) is unluckily dead. I wonder if you have other resources of these modeling data that can be shared with me? Thanks!

**Comment by a-mohsen** [comment]
Thanks for mentioning it.
Please find the following working link:
http://ijra.iaescore.com/index.php/IJRA/article/view/1001
